### ISSUE TITLE
amount in the callback

### ISSUE THREAD

**Issue by leonardodias-dev** [savvyio/savvy-samples#3]
I am having very difficult to get the actual value that was sent, if I send 0.0005 BTC, the callback shows 5000, this can end up generating big problems if it is not calculated the exact way, please help me, I want to get the real value.

**Comment by BashkaMen** [comment]
> I am having very difficult to get the actual value that was sent, if I send 0.0005 BTC, the callback shows 5000, this can end up generating big problems if it is not calculated the exact way, please help me, I want to get the real value.

5000 / 1000000000
